---
# TODO: Fix https://github.com/phan/phan/issues/826
engines:
  phan:
    enabled: true
    config:
        file_extensions: "php"
        ignore-undeclared: false
        quick: false
        backward-compatibility-checks: true
        dead-code-detection: true
exclude_patterns:
  - tests/**/*
