language: php

php:
  - 7.1

env:
  - TEST_SUITE="AnalyzerTest"
  - TEST_SUITE="PhanTest"
  - TEST_SUITE="RasmusTest"
  - TEST_SUITE="LanguageTest"
  - TEST_SUITE="OutputPrinterTest"
  - TEST_SUITE="__FakeSelfTest"

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - ./tests/setup.sh
  - composer validate

install:
  - composer --prefer-dist install

# We have a fake TEST_SUITE which runs phan, and check if the exit code is non-zero and the standard output is non-empty.
# This is used instead of a unit test because Phan currently caches too much state for this to be run with other unit tests, and the configuration might end up different within a unit test.
script:
  - if [ "$TEST_SUITE" != "__FakeSelfTest" ]; then ./vendor/bin/phpunit --colors --testsuite "$TEST_SUITE"; else ./phan ; fi
  - php package.php
